### ISSUE TITLE
Setting Hubot permissions to teams/rooms

### ISSUE THREAD

**Issue by donaldgifford** [tylerlong/glip-hubot-t#1]
Is there a setting to set or pass when running hubot with this adapter to set it to only run inside a specified room? If not is there documentation on setting a user to only be able to have specific room access and use that as the hubot username/pass?

**Comment by tylerlong** [comment]
This project is not an adapter at all. Do you mean this one: https://github.com/tylerlong/hubot-glip?

**Comment by donaldgifford** [comment]
Yes, sorry.

**Comment by tylerlong** [comment]
I suppose you are asking about Glip only because the adapter is for Glip only.

A hubot user in Glip is just a normal user. So permission control is up to Glip. You need to ask the Glip guys if this is possible. I doubt it because anybody can invite other users into a room/group.

As a workaround, you can check the room/group ID in your hubot scripts and if it's not in the whitelist just ignore the Glip messages.

**Comment by donaldgifford** [comment]
Ok cool. Yeah i know the glip guys said hubot isnt a official integration so they may not be much help but I appreciate it. 

Thanks
